require(shiny)
require(rCharts)
require(plyr)
require(lubridate)
require(ggmap)
require(ggplot2)
require(googleVis)

options(RCHARTS_LIB = 'polycharts')

shinyUI(fluidPage(
  
  tags$head(
    HTML("<title>Eurostat explorer by JPP Consulting and Training</title>"),
    tags$style(
      HTML(
        "
        .box{
        background-color:#F2F2F2;
        border-radius:5px;
        padding:10px;
        text-align:center
        }
        .box h2, .box h3,.box h4,.box h5,.box h6{
        color: #4D4D4D;
        }
        .box p{
        color: #68838B;
        }
        
        .sideBox{
        background-color:#F2F2F2;
        border-radius:5px;
        padding:3px;
        text-align:left;
        padding-left:10px;
        }
        .sideBox h2, .sideBox h3,.sideBox h4, .sideBox h5,.sideBox h6{
        color: #4D4D4D;
        }
        .sideBox p{
        color: #68838B;
        }
        
        "
      )
      )
      ),
  
  div(style="margin:0 auto; max-width:800px", 
      
      fluidRow(p(" ")),
      
      ##TITLE HEADER
      fluidRow(
        column(3,
               img(src="jpp.jpg", width = 168, height = 60)
        ),
        column(9,
               h1("Prova C28 Explorer")
        )
      ),
      
      fluidRow(p(" ")),
      
      fluidRow(
      
      ##TOP SIDEBAR
      column(3,
             div(class="sideBox",
                 h5("Analyse Eurostat booking data using simple interface"),
                 p("Please select indicators to see in action. You can also select a denominator, so that you can explore your own ratios. See below for some examples and tips"),
                 
                 hr(),
                 h5("Generate Ratios/Index"),
                 
                 #Indicator/Index/Ratio selection
                 selectInput("Num", label = h6("Choose the index to observe"),
                             choices = list("Value Added", "Turnover", "Personnel Costs", "EBITDA", "Number Employees"), selected = "Personnel Costs"),
                 
                 selectInput("Den", label = h6("Choose a denominator to generate Ratios/Index"),
                             choices = list("NONE", "Value Added", "Turnover", "Personnel costs", "EBITDA", "Number Employees"), selected = "Value Added"),
                 
                 p(""),
                 downloadButton('downloadData', 'Download current view'),

                 hr(),
                 h5("TIPS"),
                 p("Ratios are generated by dividing the top selectio by the bottom one. If you leave the second selector as 'NONE' then the raw data of the first box will be displayed"),
                 p("Example ratios:"),
                 p("ULC = Personnel costs/ Value added"),
                 p("VA/BV = Value added/ Turnover"),
                 p("PC/BV = Personnel costs/ Value added"),
                 p("EBITDA/BV = EBITDA/ Turnover"),
                 p("For indicators per employee, simply leave 'Number of Employees' as denominator"),
                 p("for example: VA per employee = Value added/ Number of Employees "),
                 p("please do consider this is very much an ALPHA prototype, any feedback welcome"),
                 p("csv file can be found at ", a(href="http://ec.europa.eu/eurostat/data/database", target ="_blank", "Eurostat"))
                 
                 
             )
      ),
      
      column(9,
             
             ##Title
             fluidRow(
               div(style="color:#36648B;padding:10px",
                   h5(textOutput("title"))
               )
             ),
             
             ##TABLE
             fluidRow(
               div(dataTableOutput(outputId="contents"), style="padding:0px; margin-top:20px")
             )
             )
      
      )
  )
))
